const ENVIRONMENTS = {
  PRODUCTION: 'production',
  DEVELOPMENT: 'development',
};

const AIRTABLE = {
  API_URL: process.env.AIR_TABLE_API_URL,
  API_KEY_NAME: 'api_key',
  API_KEY_VALUE: process.env.AIR_TABLE_API_KEY,
  CAMPAIGNS_TABLE_NAME: process.env.AIR_TABLE_CAMPAIGNS_TABLE_NAME,
  VIDEOS_TABLE_NAME: process.env.AIR_TABLE_VIDEOS_TABLE_NAME,
};

const MESSAGE_LISTENER_TYPES = {
  GET_VIDEO: 'get-video',
  GET_CAMPAIGNS: 'get_campaigns',
  CAMPAIGN_IN_PROGRESS_INJECT_PLACEHOLDER:
    'CAMPAIGN_IN_PROGRESS_INJECT_PLACEHOLDER',
  CAMPAIGN_SUCCESS_VIDEO_INJECTED_OR_NOT:
    'CAMPAIGN_SUCCESS_VIDEO_INJECTED_OR_NOT',
  GET_ACTIVE_TAB: 'get-active-tab',
  SHOW_DIALOG: 'show-dialog',
  HIDE_DIALOG: 'hide-dialog',
  CAMPAIGN_INIT: 'CAMPAIGN_INIT',
  CAMPAIGN_STARTED: 'CAMPAIGN_STARTED',
  CAMPAIGN_IN_PROGRESS: 'CAMPAIGN_IN_PROGRESS',
  CAMPAIGN_DONE: 'CAMPAIGN_DONE',
  CAMPAIGN_SUCCESS: 'CAMPAIGN_SUCCESS',
  CAMPAIGN_FAILED: 'CAMPAIGN_FAILED',
  CAMPAIGN_CANCEL: 'CAMPAIGN_CANCEL',
};

const TIMEOUTS = {
  ERROR_MESSAGE_AUTO_HIDE_TIMEOUT: 5000,
  PRE_POLLING_WAIT_TIME: 60000 * 4,
};

const DEPLOYMENT = 'DEPLOYMENT';

const POLLING = {
  MAX_TRY: 30,
  TIMEOUT: 60000,
};

const THUMBNAIL_IMAGE_URL = process.env.THUMBNAIL_IMAGE_URL;
const NODE_ENV = process.env.NODE_ENV;

const LOCAL_API_CAMPAIGNS_URL = process.env.LOCAL_API_CAMPAIGNS_URL;
const LOCAL_API_CAMPAIGN_VIDEOS_URL = process.env.LOCAL_API_CAMPAIGN_VIDEOS_URL;
const LOCAL_API_CAMPAIGN_VIDEOS_POST_URL =
  process.env.LOCAL_API_CAMPAIGN_VIDEOS_POST_URL;
const ZAPIER_POST_VIDEO_PROCESS_WEBHOOK_URL =
  process.env.ZAPIER_POST_VIDEO_PROCESS_WEBHOOK_URL;

export {
  DEPLOYMENT,
  ENVIRONMENTS,
  MESSAGE_LISTENER_TYPES,
  TIMEOUTS,
  POLLING,
  THUMBNAIL_IMAGE_URL,
  AIRTABLE,
  NODE_ENV,
  LOCAL_API_CAMPAIGNS_URL,
  LOCAL_API_CAMPAIGN_VIDEOS_URL,
  LOCAL_API_CAMPAIGN_VIDEOS_POST_URL,
  ZAPIER_POST_VIDEO_PROCESS_WEBHOOK_URL,
};
